
---
server:
  port: 8888

spring:
  security:
    user:
      name: manavpatel
      password: manavpatel
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pmanav2412/Spring_Cloud_Config
          search-paths:
          - 'station*'
#          repos:
#            perf:
#              pattern:
#              - "*/{something_to_match}"
#              uri: https://gitrepo
#       
              
     